# Generated by Django 2.0.5 on 2018-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0004_auto_20180724_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(default='1', max_length=50)),
                ('img', models.ImageField(default='', upload_to='img/')),
                ('video', models.FileField(default='', upload_to='video/')),
            ],
        ),
    ]
