# Generated by Django 2.0.5 on 2018-07-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0005_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='img',
        ),
    ]
