# Generated by Django 2.0.5 on 2018-07-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0006_remove_media_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='img',
            field=models.ImageField(default='', upload_to='img/'),
        ),
    ]
