# Generated by Django 2.0.5 on 2018-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0007_media_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendAddList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=50)),
                ('friendid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(max_length=50)),
                ('friendid', models.CharField(max_length=50)),
            ],
        ),
    ]
