# Generated by Django 2.0.5 on 2018-08-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0008_friendaddlist_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
