# Generated by Django 2.0.5 on 2018-08-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0009_auto_20180802_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='clientid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='newtest.Client'),
        ),
    ]
