# Generated by Django 2.0.5 on 2018-08-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0011_auto_20180802_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendaddlist',
            old_name='clientid2',
            new_name='clientid',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='clientid1',
            new_name='clientid',
        ),
    ]
