# Generated by Django 2.0.5 on 2018-08-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0013_auto_20180802_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
