# Generated by Django 2.0.5 on 2018-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0016_auto_20180802_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
