# Generated by Django 2.0.5 on 2018-08-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0017_auto_20180802_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.CharField(max_length=50),
        ),
    ]
