# Generated by Django 2.0.5 on 2018-08-02 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newtest', '0018_auto_20180802_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientid',
            field=models.CharField(default=uuid.uuid1, max_length=50, unique=True),
        ),
    ]
